### ISSUE TITLE
Add Video form should not have preselected options.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/be-well#146]
Should be consistent with other forms, and not be filled in by default.
Screenshot Example

![default_add_video_form](https://user-images.githubusercontent.com/11938477/194341973-d6a4d278-5927-4aee-affd-bc036a906cc9.png)

**Comment by LAlexMHllc** [comment]
NOTE: Curtis is fine with the "Save" icon, so do not change.

**Comment by zachegnermh** [comment]
https://github.com/MicroHealthLLC/be-well/pull/147

**Comment by LAlexMHllc** [comment]
Closing, fixed
